# Generated by Django 6.0.1 on 2026-08-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_sslpayment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('wallet', 'Wallet')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='sslpayment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_payment', to='users.order'),
        ),
    ]
